version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/words.sql:/docker-entrypoint-initdb.d/words.sql
    ports:
      - "5432:5432"

  words:
    build: ./words
    depends_on:
      - db
    ports:
      - "8080:8080"

  web:
    build: ./web
    depends_on:
      - words
    ports:
      - "80:80"

volumes:
  db_data: