version: "3"

services:
  redis: 
    image: redis
    ports:
      - 6379:6379
  notebook:
    build: notebook/
    ports:
      - 8888:8888
    volumes:
       - ./:/home/jovyan/work/data
    environment:
      - GRANT_SUDO=yes
      
